language: objective-c
os: osx
osx_image: xcode9.3
xcode_project: TravisCISample.xcodeproj
xcode_scheme: TravisCISample
notifications:
  email: false
  slack:
    secure: kQVTIxHv/8yzy/zOZtfgcPNRxuEzvpYPWq7G5NTW6i117ahjEkLqwYwwutVrtSWotAdmKqj82T8sPEeiWrbUaDLaRpmz83qa6RuCNIRKeiI7Qi5661r25raIsDmoPsAGmdkRGrIQkp2OGCKRW6GKK5NQcHc1UYyuWm1n7rUfpecZSL3iAYmwM1micJfZjlsaqQzMNvSqHw2mKiv6fNBLJ0IAKjZ/l9LqZuQ3xpVjMGO++pA8E03cTac+hi7LMVgKK6SRMQ3UMrjvFuDzMsyz95t3ZxlXAkkieKXtOFj3LIpqiEFL01CcN4SgcIWuy6rfxi6nMSxy4f/iLK/h6z3e/QY2yAstzw9rG6LfA0J6O8AoPQSbo4C4nsQCcY+bTU7Keg9r2m0E7G4tzu19qlSswn2QpmKGzYqHCwUpLiczCaN/879ez5Ly+IJb5ZhrrSgxgMo7XUkGtITM8GOLgIk0AH2+FeXUT8mkBUh++xPXNZ3Lj0fpHoxZ9vn3ygbEDdRW91p0a8dXUXZOF0o9+GbILgu7AfwvitU5dXgeAU1gkGetjGxFEo/Yl3h6w8SZ4iU1StreyZXiuRavfchL6jRQLqQeh9AkKq3BUAjauEfEI/C0RG49zR0is50UzxfzU3HEQ2TpMorHVqlNtDVlplwjMgLVYZSsUMWKLBFb021f/+o=
